//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_Id { get; set; }
        public string Name { get; set; }
        public string Mail_Id { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
